// <auto-generated />
using System;
using AvontuurApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AvontuurApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250310204137_AddedSeedingDataAvontuurEntry")]
    partial class AddedSeedingDataAvontuurEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AvontuurApp.Models.AvontuurEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AvontuurEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "1ste kamp met die nuwe 4x4 by 3 berge.",
                            CreatedAt = new DateTime(2025, 3, 10, 22, 41, 37, 262, DateTimeKind.Local).AddTicks(9863),
                            Location = "3 Berge kamp",
                            Title = "Eerste overland kamp"
                        },
                        new
                        {
                            Id = 2,
                            Content = "1ste 4x4 trippie.",
                            CreatedAt = new DateTime(2025, 3, 10, 22, 41, 37, 262, DateTimeKind.Local).AddTicks(9865),
                            Location = "Pilansberg",
                            Title = "Eerste 4x4"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Caos, grade 4 trail",
                            CreatedAt = new DateTime(2025, 3, 10, 22, 41, 37, 262, DateTimeKind.Local).AddTicks(9867),
                            Location = "3 Berge",
                            Title = "Uitkyk"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
